Create Luce Carević.json
ericwbailey/a11y-webring.club pull request #86
Opened 2023-02-12 16:25 UTC by luce-carevic

👋

2023-02-12 20:32 UTC, ericwbailey requested changes
Welcome! `null` can't be in quotes, otherwise it will get interpreted as a string. If you accept my suggestion it'll patch things up and you're good to be merged! 🙌

2023-02-12 20:32 UTC, ericwbailey commented on data/members/Luce Carević.json
> +  "twitter": "null"
```suggestion
  "twitter": null
```

2023-02-13 11:19 UTC, luce-carevic commented
Sorry for the mistake! 😅

2023-02-13 17:08 UTC, ericwbailey approved these changes
No worries! Welcome 🙌

2023-02-13 17:08 UTC, merged